interface ZIF_DEPARTMENTS_CDS_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZDEPARTMENTS_CDS,
 CREATE_ZDEPARTMENTS_CDS        TYPE /BOBF/ACT_KEY VALUE '0800279E4B521EEBAC9AE1CC79370B9C',
 DELETE_ZDEPARTMENTS_CDS        TYPE /BOBF/ACT_KEY VALUE '0800279E4B521EEBAC9AE1CC79378B9C',
 LOCK_ZDEPARTMENTS_CDS          TYPE /BOBF/ACT_KEY VALUE '0800279E4B521EEBAC9AE1455AB68B9C',
 SAVE_ZDEPARTMENTS_CDS          TYPE /BOBF/ACT_KEY VALUE '0800279E4B521EEBAC9AE1CC79380B9C',
 UNLOCK_ZDEPARTMENTS_CDS        TYPE /BOBF/ACT_KEY VALUE '0800279E4B521EEBAC9AE1455AB6CB9C',
 UPDATE_ZDEPARTMENTS_CDS        TYPE /BOBF/ACT_KEY VALUE '0800279E4B521EEBAC9AE1CC79374B9C',
 VALIDATE_ZDEPARTMENTS_CDS      TYPE /BOBF/ACT_KEY VALUE '0800279E4B521EEBAC9AE1CC7937CB9C',
      END OF ZDEPARTMENTS_CDS,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZDEPARTMENTS_CDS,
        BEGIN OF LOCK_ZDEPARTMENTS_CDS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZDEPARTMENTS_CDS,
        BEGIN OF UNLOCK_ZDEPARTMENTS_CDS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZDEPARTMENTS_CDS,
      END OF ZDEPARTMENTS_CDS,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZDEPARTMENTS_CDS,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '0800279E4B521EEBAC9AE53B6B078B9E',
      END OF ZDEPARTMENTS_CDS,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZDEPARTMENTS_CDS,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279E4B521EEBAC9AE1455AB66B9C',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279E4B521EEBAC9AE11E1B1C2B9C',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279E4B521EEBAC9AE16D98416B9C',
      END OF ZDEPARTMENTS_CDS,
      BEGIN OF ZDEPARTMENTS_CDS_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279E4B521EEBAC9AE1F3CE7CEB9C',
      END OF ZDEPARTMENTS_CDS_LOCK,
      BEGIN OF ZDEPARTMENTS_CDS_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279E4B521EEBAC9AE1F3CE7CCB9C',
      END OF ZDEPARTMENTS_CDS_MESSAGE,
      BEGIN OF ZDEPARTMENTS_CDS_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0800279E4B521EEBAC9AE1F3CE7D0B9C',
      END OF ZDEPARTMENTS_CDS_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZDEPARTMENTS_CDS,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZDEPARTMENTS_CDS,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0800279E4B521EEBAC9ADDC0C0014B98' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZDEPARTMENTS_CDS' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZDEPARTMENTS_CDS,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '0800279E4B521EEBAC9AE53B6B07AB9E',
      END OF ZDEPARTMENTS_CDS,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZDEPARTMENTS_CDS               TYPE /BOBF/OBM_NODE_KEY VALUE '0800279E4B521EEBAC9ADFF580568B9C',
 ZDEPARTMENTS_CDS_LOCK          TYPE /BOBF/OBM_NODE_KEY VALUE '0800279E4B521EEBAC9AE1455AB64B9C',
 ZDEPARTMENTS_CDS_MESSAGE       TYPE /BOBF/OBM_NODE_KEY VALUE '0800279E4B521EEBAC9AE11E1B1C0B9C',
 ZDEPARTMENTS_CDS_PROPERTY      TYPE /BOBF/OBM_NODE_KEY VALUE '0800279E4B521EEBAC9AE16D98414B9C',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZDEPARTMENTS_CDS,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  DEPARTMENT_ID                  TYPE STRING VALUE 'DEPARTMENT_ID',
  DEPARTMENT_NAME                TYPE STRING VALUE 'DEPARTMENT_NAME',
  DEPARTMENT_LEADER              TYPE STRING VALUE 'DEPARTMENT_LEADER',
  DEPARTMENT_ADDRESS             TYPE STRING VALUE 'DEPARTMENT_ADDRESS',
  DEPARTMENT_ROOM                TYPE STRING VALUE 'DEPARTMENT_ROOM',
      END OF ZDEPARTMENTS_CDS,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZDEPARTMENTS_CDS,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0800279E4B521EEBAC9AE0B794794B9C',
      END OF ZDEPARTMENTS_CDS,
    END OF SC_NODE_CATEGORY .
endinterface.
